export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST"
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE"

export const GET_TOTALITEM_REQUEST = "GET_TOTALITEM_REQUEST"
export const GET_TOTALITEM_SUCCESS = "GET_TOTALITEM_SUCCESS"
export const GET_TOTALITEM_FAILURE = "GET_TOTALITEM_FAILURE"

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

export const PAY_ITEM_REQUEST = "PAY_ITEM_REQUEST"
export const PAY_ITEM_SUCCESS = "PAY_ITEM_SUCCESS"
export const PAY_ITEM_FAILURE = "PAY_ITEM_FAILURE"

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST"
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE"

export const SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST"
export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS"
export const SEARCH_ITEM_FAILURE = "SEARCH_ITEM_FAILURE"

export const SEARCH_ITEMPAGINATE_REQUEST = "SEARCH_ITEMPAGINATE_REQUEST"
export const SEARCH_ITEMPAGINATE_SUCCESS = "SEARCH_ITEMPAGINATE_SUCCESS"
export const SEARCH_ITEMPAGINATE_FAILURE = "SEARCH_ITEMPAGINATE_FAILURE"

export const SEARCH_ITEMPAGINATE2_REQUEST = "SEARCH_ITEMPAGINATE2_REQUEST"
export const SEARCH_ITEMPAGINATE2_SUCCESS = "SEARCH_ITEMPAGINATE2_SUCCESS"
export const SEARCH_ITEMPAGINATE2_FAILURE = "SEARCH_ITEMPAGINATE2_FAILURE"


export const PAGINATE_ITEM_REQUEST = "PAGINATE_ITEM_REQUEST"
export const PAGINATE_ITEM_SUCCESS = "PAGINATE_ITEM_SUCCESS"
export const PAGINATE_ITEM_FAILURE = "PAGINATE_ITEM_FAILURE"

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE"

export const GET_PAY_REQUEST = "GET_PAY_REQUEST"
export const GET_PAY_SUCCESS = "GET_PAY_SUCCESS"
export const GET_PAY_FAILURE = "GET_PAY_FAILURE"
